import type { Train } from '@/types';

const now = Date.now();

export const fallbackTrains: Train[] = [
  {
    id: 'train_demo_12301',
    number: '12301',
    name: 'Howrah Rajdhani Express',
    source: 'HWH',
    destination: 'NDLS',
    status: 'ON_TIME',
    delayMinutes: 0,
    platform: 1,
    scheduledArrival: '10:00',
    expectedArrival: '10:00',
    route: ['HWH', 'DGR', 'GAYA', 'MGS', 'CNB', 'NDLS'],
    currentStationIndex: 1,
    lastUpdated: now,
    createdAt: now,
  },
  {
    id: 'train_demo_12951',
    number: '12951',
    name: 'Mumbai Rajdhani Express',
    source: 'MMCT',
    destination: 'NDLS',
    status: 'DELAYED',
    delayMinutes: 18,
    platform: 2,
    scheduledArrival: '08:35',
    expectedArrival: '08:53',
    route: ['MMCT', 'BRC', 'KOTA', 'NZM', 'NDLS'],
    currentStationIndex: 2,
    lastUpdated: now,
    createdAt: now,
  },
  {
    id: 'train_demo_12273',
    number: '12273',
    name: 'Howrah Duronto Express',
    source: 'HWH',
    destination: 'NDLS',
    status: 'ON_TIME',
    delayMinutes: 0,
    platform: 3,
    scheduledArrival: '14:20',
    expectedArrival: '14:20',
    route: ['HWH', 'ASN', 'MGS', 'CNB', 'NDLS'],
    currentStationIndex: 0,
    lastUpdated: now,
    createdAt: now,
  },
  {
    id: 'train_demo_12801',
    number: '12801',
    name: 'Purushottam Express',
    source: 'PURI',
    destination: 'NDLS',
    status: 'DELAYED',
    delayMinutes: 7,
    platform: 4,
    scheduledArrival: '21:45',
    expectedArrival: '21:52',
    route: ['PURI', 'BBS', 'KUR', 'BLS', 'HWH', 'DGR', 'ASN', 'GAYA', 'MGS', 'ALD', 'CNB', 'NDLS'],
    currentStationIndex: 4,
    lastUpdated: now,
    createdAt: now,
  },
  {
    id: 'train_demo_12627',
    number: '12627',
    name: 'Karnataka Express',
    source: 'SBC',
    destination: 'NDLS',
    status: 'CANCELLED',
    delayMinutes: 0,
    platform: 5,
    scheduledArrival: '18:30',
    expectedArrival: '18:30',
    route: ['SBC', 'KJM', 'KPD', 'MAS', 'GTL', 'LPI', 'BPQ', 'NGP', 'BPL', 'JHS', 'NDLS'],
    currentStationIndex: 0,
    lastUpdated: now,
    createdAt: now,
  },
];

export function getFallbackTrain(id: string): Train | null {
  return fallbackTrains.find((train) => train.id === id) ?? null;
}
