const STATION_LABELS: Record<string, string> = {
  NDLS: 'New Delhi',
  NZM: 'Hazrat Nizamuddin',
  HWH: 'Howrah Junction',
  SDAH: 'Sealdah',
  BWN: 'Barddhaman',
  DGR: 'Durgapur',
  ASN: 'Asansol Junction',
  KGP: 'Kharagpur Junction',
  BLS: 'Balasore',
  PURI: 'Puri',
  BBS: 'Bhubaneswar',
  KUR: 'Khurda Road',
  GAYA: 'Gaya Junction',
  DDU: 'Pt. Deen Dayal Upadhyaya Jn',
  MGS: 'Mughalsarai',
  ALD: 'Prayagraj Junction',
  PRYJ: 'Prayagraj Chheoki',
  CNB: 'Kanpur Central',
  JHS: 'Jhansi Junction',
  AGC: 'Agra Cantt',
  MTJ: 'Mathura Junction',
  GWL: 'Gwalior Junction',
  BPL: 'Bhopal Junction',
  JBP: 'Jabalpur',
  MMCT: 'Mumbai Central',
  CSMT: 'Chhatrapati Shivaji Maharaj Terminus',
  KYN: 'Kalyan Junction',
  PUNE: 'Pune Junction',
  LNL: 'Lonavala',
  SUR: 'Solapur',
  BRC: 'Vadodara Junction',
  KOTA: 'Kota Junction',
  FZR: 'Firozpur Cantt',
  LDH: 'Ludhiana Junction',
  JUC: 'Jalandhar City',
  DDN: 'Dehradun',
  RK: 'Roorkee',
  SRE: 'Saharanpur Junction',
  MTC: 'Meerut City',
  GZB: 'Ghaziabad Junction',
  MAS: 'Chennai Central',
  NLR: 'Nellore',
  BZA: 'Vijayawada Junction',
  VSKP: 'Visakhapatnam',
  RJM: 'Rajahmundry',
  SBC: 'KSR Bengaluru',
  YPR: 'Yesvantpur Junction',
  KJM: 'Krishnarajapuram',
  DMM: 'Dharmavaram Junction',
  KPD: 'Katpadi Junction',
  GTL: 'Guntakal Junction',
  LPI: 'Lingampalli',
  HYB: 'Hyderabad Deccan',
  SC: 'Secunderabad Junction',
  WADI: 'Wadi Junction',
  BPQ: 'Balharshah Junction',
  NGP: 'Nagpur Junction',
  BSP: 'Bilaspur Junction',
  RYP: 'Raipur Junction',
  RNC: 'Ranchi',
  ROU: 'Rourkela',
  DNR: 'Danapur',
};

export function getStationName(code: string): string {
  return STATION_LABELS[code] ?? code;
}

export function formatStationLabel(code: string): string {
  const name = getStationName(code);
  return name === code ? code : `${name} (${code})`;
}
